Input:
    # Sensitivity of the mouse for looking around.
    MouseSensitivity: 0.1
    # Speed of the camera for moving about.
    CameraSpeed: 0.4
Appearance:
    # Window sise in width and height.
    WindowSize: 1200, 800
    # Field of view in degrees. Avoid values >= 180.
    FieldOfView: 75
    # Back ground color in RGB float components.
    BackgroundColor: 0.2, 0.2, 0.2
    # Model color in RGB floats.
    ModelColor: 1, 0.1, 0.1
    # Diffuse intensity in each RGB float component.
    DiffuseIntensity: 0.9
    # Specular intensity in each RGB float component.
    SpecularIntensity: 0.3
    # Ambient light intensity in each float RGB component.
    AmbientIntensity: 0.1
    # How much distance affects light intensity.
    LightAttenuation: 0.2
