Input:
    # Sensitivity of the mouse for looking around.
    MouseSensitivity: 0.08
    # Speed of the camera for moving about.
    CameraSpeed: 0.2
Appearance:
    # OpenGL versions: GL20 or GL30
    GLVersion: GL30
    # Anti aliasing value for MSAA
    MSAA: 4
    # Back ground color in RGB float components.
    BackgroundColor: 0.2, 0.2, 0.2
    # AABB color in RGB floats.
    AABBColor: 0.1, 0.8, 0.1
    # Shape color for "Box" in RGB floats.
    BoxShapeColor: 0.2, 0.65, 0.69
    # Shape color for "Cone" in RGB floats.
    ConeShapeColor: 0.25, 0.25, 0.25
    # Shape color for "Cylinder" in RGB floats.
    CylinderShapeColor: 0.8, 0.1, 0.8
    # Shape color for "Sphere" in RGB floats.
    SphereShapeColor: 0.9, 0.9, 0.9
    # Diffuse intensity in float.
    DiffuseIntensity: 0.6
    # Specular intensity in float.
    SpecularIntensity: 2
    # Ambient light intensity in float.
    AmbientIntensity: 0.3
    # How much distance affects light intensity.
    LightAttenuation: 0.01
    # If back face culling is enabled
    CullingEnabled: true
